"""Reusable audio-unit bank loading for sample-based rendering."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import soundfile as sf
from scipy import signal


@dataclass(frozen=True)
class AudioUnit:
    """One reusable word/syllable unit from a voice bank."""

    key: str
    text: str
    group: str
    voice_label: str
    edge_voice: str
    gender: str
    locale: str
    wav_path: Path


class AudioUnitBank:
    """Load and cache short WAV units generated by `generate_edge_tts_units.py`."""

    def __init__(self, root: str | Path, sample_rate: int = 16_000) -> None:
        self.root = Path(root)
        self.sample_rate = sample_rate
        metadata_path = self.root / "metadata.json"
        if not metadata_path.exists():
            raise FileNotFoundError(f"Missing unit-bank metadata: {metadata_path}")

        metadata = json.loads(metadata_path.read_text())
        self.metadata = metadata
        self.units = self._load_units(metadata)
        self.units_by_voice = self._group_units_by_voice(self.units)
        self._audio_cache: dict[Path, np.ndarray] = {}

    @property
    def voice_labels(self) -> tuple[str, ...]:
        return tuple(sorted(self.units_by_voice))

    def voice_labels_for_gender(self, gender: str) -> tuple[str, ...]:
        """Return compatible TTS voice labels for a synthetic gender preset."""

        if gender == "female":
            matches = [label for label in self.voice_labels if label.startswith("female_")]
        elif gender == "male":
            matches = [label for label in self.voice_labels if label.startswith("male_")]
        else:
            matches = list(self.voice_labels)
        return tuple(matches or self.voice_labels)

    def load_audio(self, unit: AudioUnit) -> np.ndarray:
        """Return a cached mono float32 waveform for a unit."""

        path = unit.wav_path
        cached = self._audio_cache.get(path)
        if cached is not None:
            return cached

        audio, file_sample_rate = sf.read(path, always_2d=False)
        audio = np.asarray(audio, dtype=np.float32)
        if audio.ndim == 2:
            audio = np.mean(audio, axis=1)
        if file_sample_rate != self.sample_rate:
            audio = signal.resample_poly(audio, self.sample_rate, file_sample_rate).astype(np.float32)
        audio = np.nan_to_num(audio.astype(np.float32))
        self._audio_cache[path] = audio
        return audio

    def _load_units(self, metadata: dict) -> list[AudioUnit]:
        units = []
        for record in metadata.get("files", []):
            wav_path = Path(record["wav_path"])
            if not wav_path.is_absolute():
                wav_path = self.root / wav_path.relative_to(self.root) if str(wav_path).startswith(str(self.root)) else wav_path
            if not wav_path.exists():
                # Metadata from older interrupted runs can mention failed or
                # partial files. Skip missing units instead of breaking the bank.
                continue
            voice_label = str(record.get("voice_label", wav_path.parent.name))
            units.append(
                AudioUnit(
                    key=str(record.get("unit", wav_path.stem)),
                    text=str(record.get("text", wav_path.stem)),
                    group=str(record.get("group", "word")),
                    voice_label=voice_label,
                    edge_voice=str(record.get("edge_voice", "")),
                    gender=str(record.get("gender", "")) or _infer_gender_from_label(voice_label),
                    locale=str(record.get("locale", "")),
                    wav_path=wav_path,
                )
            )
        if not units:
            raise ValueError(f"No usable WAV units found in {self.root}")
        return units

    @staticmethod
    def _group_units_by_voice(units: list[AudioUnit]) -> dict[str, list[AudioUnit]]:
        grouped: dict[str, list[AudioUnit]] = {}
        for unit in units:
            grouped.setdefault(unit.voice_label, []).append(unit)
        for voice_units in grouped.values():
            voice_units.sort(key=lambda item: item.key)
        return grouped


def _infer_gender_from_label(label: str) -> str:
    if label.startswith("female_"):
        return "Female"
    if label.startswith("male_"):
        return "Male"
    return ""
